package main

type EnumCommandResultName string

const (
	EnumCommandResultNamecore_ping           EnumCommandResultName = "core.ping"
	EnumCommandResultNamecore_system         EnumCommandResultName = "core.system"
	EnumCommandResultNamecore_kill           EnumCommandResultName = "core.kill"
	EnumCommandResultNamecore_killall        EnumCommandResultName = "core.killall"
	EnumCommandResultNamecore_state          EnumCommandResultName = "core.state"
	EnumCommandResultNamecore_reboot         EnumCommandResultName = "core.reboot"
	EnumCommandResultNameinfo_cpu            EnumCommandResultName = "info.cpu"
	EnumCommandResultNameinfo_disk           EnumCommandResultName = "info.disk"
	EnumCommandResultNameinfo_mem            EnumCommandResultName = "info.mem"
	EnumCommandResultNameinfo_nic            EnumCommandResultName = "info.nic"
	EnumCommandResultNameinfo_os             EnumCommandResultName = "info.os"
	EnumCommandResultNamecorex_create        EnumCommandResultName = "corex.create"
	EnumCommandResultNamecorex_list          EnumCommandResultName = "corex.list"
	EnumCommandResultNamecorex_dispatch      EnumCommandResultName = "corex.dispatch"
	EnumCommandResultNamecorex_terminate     EnumCommandResultName = "corex.terminate"
	EnumCommandResultNamebridge_create       EnumCommandResultName = "bridge.create"
	EnumCommandResultNamebridge_list         EnumCommandResultName = "bridge.list"
	EnumCommandResultNamebridge_delete       EnumCommandResultName = "bridge.delete"
	EnumCommandResultNamedisk_list           EnumCommandResultName = "disk.list"
	EnumCommandResultNamedisk_mktable        EnumCommandResultName = "disk.mktable"
	EnumCommandResultNamedisk_mkpart         EnumCommandResultName = "disk.mkpart"
	EnumCommandResultNamedisk_rmpart         EnumCommandResultName = "disk.rmpart"
	EnumCommandResultNamedisk_mount          EnumCommandResultName = "disk.mount"
	EnumCommandResultNamedisk_umount         EnumCommandResultName = "disk.umount"
	EnumCommandResultNamebtrfs_create        EnumCommandResultName = "btrfs.create"
	EnumCommandResultNamebtrfs_list          EnumCommandResultName = "btrfs.list"
	EnumCommandResultNamebtrfs_subvol_create EnumCommandResultName = "btrfs.subvol_create"
	EnumCommandResultNamebtrfs_subvol_list   EnumCommandResultName = "btrfs.subvol_list"
	EnumCommandResultNamebtrfs_subvol_delete EnumCommandResultName = "btrfs.subvol_delete"
)
