package node

type EnumJobResultName string

const (
	EnumJobResultNamecore_ping           EnumJobResultName = "core.ping"
	EnumJobResultNamecore_system         EnumJobResultName = "core.system"
	EnumJobResultNamecore_kill           EnumJobResultName = "core.kill"
	EnumJobResultNamecore_killall        EnumJobResultName = "core.killall"
	EnumJobResultNamecore_state          EnumJobResultName = "core.state"
	EnumJobResultNamecore_reboot         EnumJobResultName = "core.reboot"
	EnumJobResultNameinfo_cpu            EnumJobResultName = "info.cpu"
	EnumJobResultNameinfo_disk           EnumJobResultName = "info.disk"
	EnumJobResultNameinfo_mem            EnumJobResultName = "info.mem"
	EnumJobResultNameinfo_nic            EnumJobResultName = "info.nic"
	EnumJobResultNameinfo_os             EnumJobResultName = "info.os"
	EnumJobResultNamecontainer_create    EnumJobResultName = "container.create"
	EnumJobResultNamecontainer_list      EnumJobResultName = "container.list"
	EnumJobResultNamecontainer_dispatch  EnumJobResultName = "container.dispatch"
	EnumJobResultNamecontainer_terminate EnumJobResultName = "container.terminate"
	EnumJobResultNamebridge_create       EnumJobResultName = "bridge.create"
	EnumJobResultNamebridge_list         EnumJobResultName = "bridge.list"
	EnumJobResultNamebridge_delete       EnumJobResultName = "bridge.delete"
	EnumJobResultNamedisk_list           EnumJobResultName = "disk.list"
	EnumJobResultNamedisk_mktable        EnumJobResultName = "disk.mktable"
	EnumJobResultNamedisk_mkpart         EnumJobResultName = "disk.mkpart"
	EnumJobResultNamedisk_rmpart         EnumJobResultName = "disk.rmpart"
	EnumJobResultNamedisk_mount          EnumJobResultName = "disk.mount"
	EnumJobResultNamedisk_umount         EnumJobResultName = "disk.umount"
	EnumJobResultNamebtrfs_create        EnumJobResultName = "btrfs.create"
	EnumJobResultNamebtrfs_list          EnumJobResultName = "btrfs.list"
	EnumJobResultNamebtrfs_subvol_create EnumJobResultName = "btrfs.subvol_create"
	EnumJobResultNamebtrfs_subvol_list   EnumJobResultName = "btrfs.subvol_list"
	EnumJobResultNamebtrfs_subvol_delete EnumJobResultName = "btrfs.subvol_delete"
)
