package volume

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// VolumesInterface is interface for /volumes root endpoint
type VolumesInterface interface { // CreateNewVolume is the handler for POST /volumes
	// Create a new volume, can be a copy from an existing volume
	CreateNewVolume(http.ResponseWriter, *http.Request)
	// GetVolumeInfo is the handler for GET /volumes/{volumeid}
	// Get volume information
	GetVolumeInfo(http.ResponseWriter, *http.Request)
	// DeleteVolume is the handler for DELETE /volumes/{volumeid}
	// Delete Volume
	DeleteVolume(http.ResponseWriter, *http.Request)
	// ResizeVolume is the handler for POST /volumes/{volumeid}/resize
	// Resize Volume
	ResizeVolume(http.ResponseWriter, *http.Request)
	// RollbackVolume is the handler for POST /volumes/{volumeid}/rollback
	// Rollback a volume to a previous state
	RollbackVolume(http.ResponseWriter, *http.Request)
}

// VolumesInterfaceRoutes is routing for /volumes root endpoint
func VolumesInterfaceRoutes(r *mux.Router, i VolumesInterface) {
	r.HandleFunc("/volumes", i.CreateNewVolume).Methods("POST")
	r.HandleFunc("/volumes/{volumeid}", i.GetVolumeInfo).Methods("GET")
	r.HandleFunc("/volumes/{volumeid}", i.DeleteVolume).Methods("DELETE")
	r.HandleFunc("/volumes/{volumeid}/resize", i.ResizeVolume).Methods("POST")
	r.HandleFunc("/volumes/{volumeid}/rollback", i.RollbackVolume).Methods("POST")
}
